title: "YFACC: Yorùbá Flickr Audio Caption Corpus"
description: A Yorùbá speech-image dataset for cross-lingual keyword localisation through visual grounding
show_downloads: false
theme: jekyll-theme-slate
